spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: ${DB_LOGIN}
    password: ${DB_PASS}
    url: ${DB_URL}
bot:
  token: ${BOT_TOKEN}
  chat-id: ${BOT_CHAT_ID}